FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y python3 python3-dev python3-pip libsm6 libxext6 libxrender-dev vim\
    software-properties-common build-essential libpoppler-cpp-dev poppler-utils pkg-config

RUN add-apt-repository ppa:alex-p/tesseract-ocr && apt-get update -y && apt-get install tesseract-ocr -y

RUN apt-get clean

WORKDIR /deploy
COPY run_debug.py /deploy/run_debug.py
RUN mkdir -p /deploy/app
COPY app/ /deploy/app
COPY requirements.txt /deploy/
RUN pip3 install -r /deploy/requirements.txt

ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED=1
ENV OMP_THREAD_LIMIT=1

CMD ["python3", "-u", "run_debug.py"]